/*
 * Decompiled with CFR 0.152.
 */
package app.b;

import daff.a.e;
import daff.net.m;

/*
 * Illegal identifiers - consider using --renameillegalidents true
 */
public class b
extends m {
    public static final b ay = new b(0, new e(0), null);
    public static final int a8 = 1;
    public static final int g = 2;
    public static final int dc = 3;
    public static final int ag = 4;
    public static final int cK = 5;
    public static final int ap = 6;
    public static final int eo = 10;
    public static final int o = 1;
    public static final int f4 = 2;
    public static final int ah = 3;
    public static final int fg = 4;
    public static final int dF = 5;
    public static final int bc = 11;
    public static final int gU = 12;
    public static final int c8 = 13;
    public static final int bK = 14;
    public static final int eE = 15;
    public static final int B = 16;
    public static final int dO = 20;
    public static final int A = 30;
    public static final int gz = 31;
    public static final int gL = 256;
    public static final int gJ = 257;
    public static final int u = 258;
    public static final int s = 259;
    public static final int fc = 260;
    public static final int J = 261;
    public static final int a3 = 262;
    public static final int j = 263;
    public static final int au = 265;
    public static final int cE = 266;
    public static final int gN = 267;
    public static final int eL = 268;
    public static final int bD = 270;
    public static final int aR = 271;
    public static final int bU = 272;
    public static final int gS = 256;
    public static final int cA = 257;
    public static final int eC = 258;
    public static final int fb = 259;
    public static final int bZ = 260;
    public static final int fW = 261;
    public static final int else = 262;
    public static final int dP = 263;
    public static final int gn = 264;
    public static final int fr = 265;
    public static final int aL = 266;
    public static final int ak = 267;
    public static final int b2 = 268;
    public static final int cB = 269;
    public static final int gd = 270;
    public static final int da = 271;
    public static final int ec = 272;
    public static final int eq = 273;
    public static final int q = 274;
    public static final int gg = 275;
    public static final int t = 276;
    public static final int aD = 277;
    public static final int fK = 278;
    public static final int eN = 279;
    public static final int ew = 280;
    public static final int gE = 281;
    public static final int dk = 282;
    public static final int dW = 283;
    public static final int en = 284;
    public static final int cN = 285;
    public static final int H = 286;
    public static final int eD = 287;
    public static final int ed = 288;
    public static final int bB = 289;
    public static final int fn = 290;
    public static final int cz = 291;
    public static final int f3 = 292;
    public static final int n = 293;
    public static final int fj = 294;
    public static final int P = 295;
    public static final int a2 = 296;
    public static final int cC = 512;
    public static final int bl = 513;
    public static final int gu = 514;
    public static final int dD = 515;
    public static final int fT = 516;
    public static final int c5 = 517;
    public static final int fl = 518;
    public static final int T = 519;
    public static final int d3 = 520;
    public static final int byte = 521;
    public static final int gO = 522;
    public static final int C = 523;
    public static final int F = 524;
    public static final int c3 = 525;
    public static final int dL = 526;
    public static final int eg = 527;
    public static final int dQ = 528;
    public static final int fR = 529;
    public static final int M = 530;
    public static final int gp = 531;
    public static final int cT = 532;
    public static final int long = 533;
    public static final int c9 = 534;
    public static final int aP = 535;
    public static final int c2 = 536;
    public static final int at = 539;
    public static final int fV = 540;
    public static final int bO = 541;
    public static final int fz = 542;
    public static final int gh = 543;
    public static final int dm = 544;
    public static final int gv = 545;
    public static final int cq = 546;
    public static final int ba = 547;
    public static final int fd = 548;
    public static final int fU = 549;
    public static final int gj = 550;
    public static final int gi = 551;
    public static final int ep = 552;
    public static final int ch = 553;
    public static final int U = 554;
    public static final int ck = 555;
    public static final int dj = 556;
    public static final int cx = 557;
    public static final int ei = 558;
    public static final int bH = 559;
    public static final int fH = 560;
    public static final int ce = 561;
    public static final int bo = 562;
    public static final int co = 563;
    public static final int ax = 564;
    public static final int fw = 565;
    public static final int ct = 566;
    public static final int fZ = 567;
    public static final int bv = 568;
    public static final int dZ = 569;
    public static final int cu = 570;
    public static final int cS = 571;
    public static final int cb = 572;
    public static final int cr = 573;
    public static final int b4 = 574;
    public static final int df = 575;
    public static final int go = 576;
    public static final int e7 = 577;
    public static final int bb = 578;
    public static final int gG = 579;
    public static final int bS = 580;
    public static final int aX = 581;
    public static final int aS = 582;
    public static final int ej = 512;
    public static final int Q = 513;
    public static final int dl = 514;
    public static final int for = 515;
    public static final int e0 = 516;
    public static final int bj = 517;
    public static final int ab = 518;
    public static final int bL = 519;
    public static final int fS = 520;
    public static final int aZ = 521;
    public static final int aV = 522;
    public static final int eU = 523;
    public static final int ex = 524;
    public static final int eu = 525;
    public static final int cw = 526;
    public static final int X = 527;
    public static final int dR = 528;
    public static final int dy = 529;
    public static final int as = 530;
    public static final int aA = 531;
    public static final int eR = 533;
    public static final int void = 534;
    public static final int eb = 535;
    public static final int b = 536;
    public static final int bp = 537;
    public static final int new = 538;
    public static final int aU = 539;
    public static final int br = 540;
    public static final int ey = 541;
    public static final int eQ = 542;
    public static final int f5 = 543;
    public static final int fI = 544;
    public static final int gb = 545;
    public static final int c0 = 546;
    public static final int gT = 549;
    public static final int gw = 550;
    public static final int b7 = 551;
    public static final int cj = 552;
    public static final int gM = 553;
    public static final int dq = 554;
    public static final int fG = 555;
    public static final int e = 556;
    public static final int aO = 557;
    public static final int bk = 558;
    public static final int de = 559;
    public static final int c6 = 560;
    public static final int cO = 561;
    public static final int fJ = 562;
    public static final int by = 563;
    public static final int d9 = 564;
    public static final int d2 = 565;
    public static final int eT = 566;
    public static final int fM = 567;
    public static final int ai = 568;
    public static final int dv = 569;
    public static final int cH = 570;
    public static final int al = 571;
    public static final int dE = 572;
    public static final int d4 = 573;
    public static final int gC = 574;
    public static final int cX = 575;
    public static final int d5 = 576;
    public static final int bM = 577;
    public static final int h = 578;
    public static final int ds = 579;
    public static final int fh = 580;
    public static final int a7 = 581;
    public static final int fu = 582;
    public static final int cc = 583;
    public static final int G = 584;
    public static final int fk = 585;
    public static final int r = 586;
    public static final int cd = 587;
    public static final int e2 = 588;
    public static final int aY = 589;
    public static final int cl = 590;
    public static final int aF = 591;
    public static final int gr = 592;
    public static final int e3 = 593;
    public static final int fq = 594;
    public static final int bE = 595;
    public static final int gs = 596;
    public static final int bx = 597;
    public static final int bd = 598;
    public static final int V = 599;
    public static final int Z = 600;
    public static final int y = 601;
    public static final int bY = 602;
    public static final int e6 = 603;
    public static final int cU = 604;
    public static final int et = 605;
    public static final int fL = 606;
    public static final int dY = 768;
    public static final int bR = 769;
    public static final int e1 = 770;
    public static final int O = 771;
    public static final int fY = 772;
    public static final int cG = 773;
    public static final int af = 774;
    public static final int e5 = 768;
    public static final int fO = 769;
    public static final int gx = 770;
    public static final int cQ = 771;
    public static final int er = 772;
    public static final int fB = 773;
    public static final int bT = 774;
    public static final int ee = 1024;
    public static final int em = 1025;
    public static final int ac = 1026;
    public static final int c1 = 1024;
    public static final int a5 = 1025;
    public static final int dJ = 1026;
    public static final int dM = 1280;
    public static final int dn = 1281;
    public static final int aa = 1282;
    public static final int cF = 1283;
    public static final int eX = 1280;
    public static final int gA = 1281;
    public static final int fA = 1282;
    public static final int S = 1283;
    public static final int ge = 1284;
    public static final int dB = 1285;
    public static final int l = 1536;
    public static final int bh = 1537;
    public static final int dd = 1538;
    public static final int ga = 1539;
    public static final int bX = 1540;
    public static final int aI = 1536;
    public static final int aq = 1537;
    public static final int bs = 1538;
    public static final int eI = 1539;
    public static final int eS = 1540;
    public static final int aC = 1541;
    public static final int W = 1542;
    public static final int gQ = 1543;
    public static final int bm = 1544;
    public static final int du = 1545;
    public static final int gD = 1546;
    public static final int dp = 1547;
    public static final int bI = 1548;
    public static final int fx = 1549;
    public static final int eY = 1792;
    public static final int ef = 1793;
    public static final int dK = 1794;
    public static final int cW = 1795;
    public static final int K = 1796;
    public static final int gR = 1797;
    public static final int i = 1798;
    public static final int bi = 1799;
    public static final int bW = 1800;
    public static final int ft = 1801;
    public static final int eH = 1802;
    public static final int gB = 1803;
    public static final int az = 1804;
    public static final int bn = 1805;
    public static final int d0 = 1806;
    public static final int dN = 1807;
    public static final int I = 1808;
    public static final int d7 = 1809;
    public static final int bq = 1810;
    public static final int cn = 1811;
    public static final int dC = 1812;
    public static final int dI = 1813;
    public static final int gm = 1814;
    public static final int cp = 1815;
    public static final int eB = 1816;
    public static final int fp = 1817;
    public static final int cm = 1818;
    public static final int bg = 1819;
    public static final int e9 = 1792;
    public static final int dH = 1793;
    public static final int di = 1794;
    public static final int D = 1795;
    public static final int ae = 1796;
    public static final int bA = 1797;
    public static final int aK = 1798;
    public static final int gH = 1799;
    public static final int ar = 1800;
    public static final int dS = 1801;
    public static final int L = 1802;
    public static final int aW = 1803;
    public static final int eh = 1804;
    public static final int aM = 1805;
    public static final int dU = 1806;
    public static final int bu = 1807;
    public static final int w = 1808;
    public static final int dt = 1809;
    public static final int b6 = 1810;
    public static final int dx = 1811;
    public static final int dA = 1812;
    public static final int c7 = 1813;
    public static final int int = 1814;
    public static final int cV = 1815;
    public static final int dg = 1816;
    public static final int a4 = 1817;
    public static final int dX = 1818;
    public static final int dw = 1819;
    public static final int bQ = 1820;
    public static final int d = 1821;
    public static final int gI = 1822;
    public static final int R = 1823;
    public static final int eM = 2048;
    public static final int gK = 2049;
    public static final int gt = 2050;
    public static final int cY = 2051;
    public static final int fy = 2052;
    public static final int gy = 2053;
    public static final int eP = 2048;
    public static final int bN = 2049;
    public static final int fm = 2050;
    public static final int e8 = 2051;
    public static final int dG = 2052;
    public static final int bV = 2053;
    public static final int ek = 2054;
    public static final int z = 2055;
    public static final int k = 2056;
    public static final int fs = 2057;
    public static final int f9 = 2058;
    public static final int eZ = 2304;
    public static final int bC = 2305;
    public static final int cZ = 2306;
    public static final int eK = 2307;
    public static final int cP = 2308;
    public static final int e4 = 2310;
    public static final int case = 2311;
    public static final int gc = 2312;
    public static final int f8 = 2313;
    public static final int aH = 2314;
    public static final int es = 2315;
    public static final int bJ = 2316;
    public static final int gf = 2317;
    public static final int cD = 2318;
    public static final int a1 = 2319;
    public static final int fa = 2320;
    public static final int v = 2321;
    public static final int fE = 2322;
    public static final int cs = 2323;
    public static final int bz = 2324;
    public static final int f2 = 2325;
    public static final int bw = 2326;
    public static final int p = 2327;
    public static final int fe = 2328;
    public static final int a0 = 2329;
    public static final int gq = 2330;
    public static final int ez = 2331;
    public static final int x = 2332;
    public static final int try = 2333;
    public static final int fF = 2334;
    public static final int c = 2335;
    public static final int b1 = 2336;
    public static final int ci = 2337;
    public static final int aB = 2338;
    public static final int cf = 2339;
    public static final int bG = 2340;
    public static final int fQ = 2341;
    public static final int dz = 2342;
    public static final int fv = 2343;
    public static final int ea = 2344;
    public static final int eF = 2345;
    public static final int f6 = 2346;
    public static final int cR = 2347;
    public static final int cM = 2348;
    public static final int Y = 2349;
    public static final int fP = 2350;
    public static final int an = 2351;
    public static final int a9 = 2352;
    public static final int ff = 2353;
    public static final int E = 2354;
    public static final int aj = 2355;
    public static final int fN = 2356;
    public static final int fD = 2357;
    public static final int bF = 2358;
    public static final int gP = 2359;
    public static final int dh = 2370;
    public static final int aw = 2371;
    public static final int el = 2372;
    public static final int aN = 2373;
    public static final int eV = 2374;
    public static final int gF = 2375;
    public static final int aT = 2376;
    public static final int ev = 2377;
    public static final int a6 = 2378;
    public static final int gl = 2379;
    public static final int b8 = 2380;
    public static final int d1 = 2381;
    public static final int f0 = 2382;
    public static final int d6 = 2383;
    public static final int goto = 2384;
    public static final int fX = 2385;
    public static final int fo = 2386;
    public static final int eO = 2387;
    public static final int be = 2388;
    public static final int gk = 2389;
    public static final int eA = 2390;
    public static final int ca = 2391;
    public static final int db = 2392;
    public static final int m = 2393;
    public static final int aE = 2394;
    public static final int cJ = 2395;
    public static final int aG = 2304;
    public static final int fC = 2305;
    public static final int bP = 2306;
    public static final int b9 = 2560;
    public static final int dV = 2561;
    public static final int f1 = 2562;
    public static final int cL = 2563;
    public static final int d8 = 2564;
    public static final int f = 2565;
    public static final int b0 = 2566;
    public static final int cI = 2567;
    public static final int eW = 2568;
    public static final int dT = 2569;
    public static final int b3 = 2570;
    public static final int ad = 2571;
    public static final int ao = 2572;
    public static final int b5 = 2573;
    public static final int char = 2574;
    public static final int cg = 2560;
    public static final int cy = 2561;
    public static final int eJ = 2562;
    public static final int f7 = 2563;
    public static final int do = 2564;
    public static final int dr = 2565;
    public static final int N = 3072;
    public static final int fi = 3073;
    public static final int bt = 3074;
    public static final int av = 3075;
    public static final int aJ = 3328;
    public static final int c4 = 3329;
    public static final int aQ = 3330;
    public static final int bf = 3584;
    public static final int eG = 3585;
    public static final int cv = 3586;
    private int am;

    public static final int new() {
        return 20091031;
    }

    public String toString() {
        e e2 = this.for();
        if (e2 == null) {
            return "AppMessage[type=" + Integer.toHexString(this.am) + ";buffer=null]";
        }
        return "AppMessage[type=" + Integer.toHexString(this.am) + ";length=" + this.for().goto() + ";capacity=" + this.for().try() + "]";
    }

    public b(int n2) {
        this(n2, 256);
    }

    public b(int n2, int n3) {
        this(n2, new e(n3), null);
    }

    public b(int n2, e e2) {
        this(n2, e2, null);
    }

    public b(int n2, e e2, Object object) {
        super(e2, object);
        this.am = n2;
    }

    public e for() {
        return (e)this.a();
    }

    public b int() {
        e e2 = this.for();
        e e3 = new e(e2.goto());
        e3.a(e2);
        b b2 = new b(this.am, e3);
        return b2;
    }

    public int do() {
        return this.am;
    }

    public void a(int n2) {
        this.am = n2;
    }
}

